### ISSUE TITLE
Filter for TCGA-LUSC download

### ISSUE THREAD

**Issue by hugoych** [NYUMedML/conditional_ssl_hist#1]
Hi, 
Thanks for your work and easy-to-follow repo!
I think there was a small issue with the TCGA-LUSC filter link in your README. 

I was just skimming through it and I think you forgot to add the diagnostic slides to the filter from the TCGA-LUSC download link. 
Indeed with the current [link](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-LUSC%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_format%22%2C%22value%22%3A%5B%22svs%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Tissue%20Slide%22%5D%7D%7D%5D%7D), there are only 495 patients as opposed to what is mentioned in the manuscript with 504 samples. 

I think this is because you forgot to click add the Diagnostic images to the filter. (see image below)
![image](https://user-images.githubusercontent.com/29702745/160098689-cf6c8a00-9e28-49b5-9ee5-c09262dce573.png)

When I add these slides I indeed obtain 504 patients as reported in your manuscript. Here is the [link](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-LUSC%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_format%22%2C%22value%22%3A%5B%22svs%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%2C%22Tissue%20Slide%22%5D%7D%7D%5D%7D) for the filter.

**Comment by jackzhu727** [comment]
Thanks for the careful reading! 504 is the total number of patients in TCGA-LUSC. We actually only used the tissue slide, since some previous work treated tissue and diagnostic slides differently.  We also exclude the normal slides and new tumors that don't belong to recurrence.
