### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by jafarinia** [NYUMedML/conditional_ssl_hist#3]
Hi.
Thanks for your work and open source code.
I have a few problems with feature extraction part of of your repository And your help is much appreciated.
As we can see in extract_embeddings.py there are some necessary files and I have some questions about them:
1- ./pretrained/checkpoint.pth.tar: I think this is the last (or maybe the best) checkpoint we got from previous step (Self-supervised learning). Am I right?
2- ./subtype_cls/checkpoint.pth.tar: Where does this come from? Is it exactly the same as ./pretrained/checkpoint.pth.tar? If yes then why the paths are different?
3- ../TCGA/recurrence_annotation.pkl, ../CPTAC/recurrence_annotation.pkl: I think these are obtained from TCGA and CPTAC and you were not allowed to make them public but unfortunately I don’t think they are available on their websites in the format that you used. Can you explain what is the format for these files that you serialized and what parts of TCGA/CPTAC you used for these? (based on your code I can say 2 of them are probably “category” and “case_submitter_id” but I can't tell the rest and specially the part that says the time for recurrence If that had happened for the patient) And if you think you’re allowed send a screenshot or something of a tiny fraction of it? (for example for a sample)

**Comment by jackzhu727** [comment]
1. Yes.
2. subtype_cls/checkpoint.pth.tar is a network that classifies whether a tile is a tumor or not. As mentioned in the paper, we want to exclude tiles without tumors. Here's a reference https://github.com/ncoudray/DeepPATH.
3. We update the preprocessing code to parse the downloaded csv files to recurrence_annotation.pkl.  
Items in the annotation dicts are parsed by transform in https://github.com/NYUMedML/conditional_ssl_hist/blob/main/survival_models/utils.py.
