### ISSUE TITLE
Epochs

### ISSUE THREAD

**Issue by jafarinia** [NYUMedML/conditional_ssl_hist#4]
There is a part of your code that I don’t know if you have noticed/changed for your paper’s final results or not but I thought it may help. In the code you set default for epochs = 200 and you save checkpoints for every epoch number that % 50 = 0 but because you use python range() function the last epoch number is going to be 199 so your last epoch’s result is not going to get saved  and you lose your last 50 epochs. I hope this helps.

**Comment by jackzhu727** [comment]
Thanks, fix the bug.
